// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetPdf.Context;

#nullable disable

namespace NetPdf.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250113184940_Primera Migracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetPdf.entities.Empleado", b =>
                {
                    b.Property<int>("idEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEmpleado"));

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Sueldo")
                        .HasColumnType("int");

                    b.Property<int>("idPerfil")
                        .HasColumnType("int");

                    b.HasKey("idEmpleado");

                    b.HasIndex("idPerfil");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("NetPdf.entities.Perfil", b =>
                {
                    b.Property<int>("idPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPerfil"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idPerfil");

                    b.ToTable("Perfil", (string)null);

                    b.HasData(
                        new
                        {
                            idPerfil = 1,
                            Nombre = "Nilo"
                        });
                });

            modelBuilder.Entity("NetPdf.entities.Empleado", b =>
                {
                    b.HasOne("NetPdf.entities.Perfil", "PerfilReferencia")
                        .WithMany("EmpleadosReferencia")
                        .HasForeignKey("idPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilReferencia");
                });

            modelBuilder.Entity("NetPdf.entities.Perfil", b =>
                {
                    b.Navigation("EmpleadosReferencia");
                });
#pragma warning restore 612, 618
        }
    }
}
